services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: duynguyen123#
      MYSQL_DATABASE: commission_system

    ports:
      - "3308:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./com-be
    container_name: springboot-container

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql

  frontend:
    build: ./com-fe
    container_name: angular-container

    restart: always

    ports:
      - "80:80"

    depends_on:
      - backend

volumes:
  mysql-data: