spring:
  application:
    name: com-be

  datasource:
    url: jdbc:mysql://localhost:3306/commission_system?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: duynguyen123#

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

app:
  jwt:
    secret: "commission-system-secret-key-please-change-1234567890"
    ttl-seconds: 86400
